---
- name: Un-Install Apache on Ubuntu
  hosts: host1, host2
  become: yes

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Un-Install Apache
      apt:
        name: apache2*
        state: absent
